# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/John/Desktop/reconfig/reconfig/final_lab/final_lab_vivado/final_lab/final_lab.srcs/sources_1/bd/block_design/ip/block_design_accelerator_0_0/block_design_accelerator_0_0.xci
# IP: The module: 'block_design_accelerator_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/John/Desktop/reconfig/reconfig/final_lab/final_lab_vivado/final_lab/final_lab.gen/sources_1/bd/block_design/ip/block_design_accelerator_0_0/src/fifo_32/fifo_32.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_32 || ORIG_REF_NAME==fifo_32} -quiet] -quiet

# IP: c:/Users/John/Desktop/reconfig/reconfig/final_lab/final_lab_vivado/final_lab/final_lab.gen/sources_1/bd/block_design/ip/block_design_accelerator_0_0/src/fifo_32_prog_full/fifo_32_prog_full.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_32_prog_full || ORIG_REF_NAME==fifo_32_prog_full} -quiet] -quiet

# XDC: c:/Users/John/Desktop/reconfig/reconfig/final_lab/final_lab_vivado/final_lab/final_lab.gen/sources_1/bd/block_design/ip/block_design_accelerator_0_0/src/fifo_32/fifo_32.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_32 || ORIG_REF_NAME==fifo_32} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/John/Desktop/reconfig/reconfig/final_lab/final_lab_vivado/final_lab/final_lab.gen/sources_1/bd/block_design/ip/block_design_accelerator_0_0/src/fifo_32/fifo_32_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_32 || ORIG_REF_NAME==fifo_32} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/John/Desktop/reconfig/reconfig/final_lab/final_lab_vivado/final_lab/final_lab.gen/sources_1/bd/block_design/ip/block_design_accelerator_0_0/src/fifo_32_prog_full/fifo_32_prog_full.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_32_prog_full || ORIG_REF_NAME==fifo_32_prog_full} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/John/Desktop/reconfig/reconfig/final_lab/final_lab_vivado/final_lab/final_lab.gen/sources_1/bd/block_design/ip/block_design_accelerator_0_0/src/fifo_32_prog_full/fifo_32_prog_full_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_32_prog_full || ORIG_REF_NAME==fifo_32_prog_full} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: c:/Users/John/Desktop/reconfig/reconfig/final_lab/final_lab_vivado/final_lab/final_lab.srcs/sources_1/bd/block_design/ip/block_design_accelerator_0_0/block_design_accelerator_0_0.xci
# IP: The module: 'block_design_accelerator_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/John/Desktop/reconfig/reconfig/final_lab/final_lab_vivado/final_lab/final_lab.gen/sources_1/bd/block_design/ip/block_design_accelerator_0_0/src/fifo_32/fifo_32.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_32 || ORIG_REF_NAME==fifo_32} -quiet] -quiet

# IP: c:/Users/John/Desktop/reconfig/reconfig/final_lab/final_lab_vivado/final_lab/final_lab.gen/sources_1/bd/block_design/ip/block_design_accelerator_0_0/src/fifo_32_prog_full/fifo_32_prog_full.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_32_prog_full || ORIG_REF_NAME==fifo_32_prog_full} -quiet] -quiet

# XDC: c:/Users/John/Desktop/reconfig/reconfig/final_lab/final_lab_vivado/final_lab/final_lab.gen/sources_1/bd/block_design/ip/block_design_accelerator_0_0/src/fifo_32/fifo_32.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_32 || ORIG_REF_NAME==fifo_32} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/John/Desktop/reconfig/reconfig/final_lab/final_lab_vivado/final_lab/final_lab.gen/sources_1/bd/block_design/ip/block_design_accelerator_0_0/src/fifo_32/fifo_32_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_32 || ORIG_REF_NAME==fifo_32} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/John/Desktop/reconfig/reconfig/final_lab/final_lab_vivado/final_lab/final_lab.gen/sources_1/bd/block_design/ip/block_design_accelerator_0_0/src/fifo_32_prog_full/fifo_32_prog_full.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_32_prog_full || ORIG_REF_NAME==fifo_32_prog_full} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/John/Desktop/reconfig/reconfig/final_lab/final_lab_vivado/final_lab/final_lab.gen/sources_1/bd/block_design/ip/block_design_accelerator_0_0/src/fifo_32_prog_full/fifo_32_prog_full_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_32_prog_full || ORIG_REF_NAME==fifo_32_prog_full} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
