# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/part3/part3.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==part3 || ORIG_REF_NAME==part3} -quiet] -quiet

# IP: bd/part3/ip/part3_processing_system7_0_0/part3_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==part3_processing_system7_0_0 || ORIG_REF_NAME==part3_processing_system7_0_0} -quiet] -quiet

# IP: bd/part3/ip/part3_ps7_0_axi_periph_0/part3_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==part3_ps7_0_axi_periph_0 || ORIG_REF_NAME==part3_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/part3/ip/part3_rst_ps7_0_100M_0/part3_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==part3_rst_ps7_0_100M_0 || ORIG_REF_NAME==part3_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/part3/ip/part3_accelerator_0_0/part3_accelerator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==part3_accelerator_0_0 || ORIG_REF_NAME==part3_accelerator_0_0} -quiet] -quiet

# IP: bd/part3/ip/part3_auto_pc_0/part3_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==part3_auto_pc_0 || ORIG_REF_NAME==part3_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/John/Desktop/reconig/reconfig/lab5/part3/lab5part3_vivado/lab5part3_vivado.gen/sources_1/bd/part3/part3_ooc.xdc
