# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/block_design/block_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design || ORIG_REF_NAME==block_design} -quiet] -quiet

# IP: bd/block_design/ip/block_design_processing_system7_0_0/block_design_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_processing_system7_0_0 || ORIG_REF_NAME==block_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/block_design/ip/block_design_ps7_0_axi_periph_0/block_design_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==block_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/block_design/ip/block_design_rst_ps7_0_125M_0/block_design_rst_ps7_0_125M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_rst_ps7_0_125M_0 || ORIG_REF_NAME==block_design_rst_ps7_0_125M_0} -quiet] -quiet

# IP: bd/block_design/ip/block_design_accelerator_0_0/block_design_accelerator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_accelerator_0_0 || ORIG_REF_NAME==block_design_accelerator_0_0} -quiet] -quiet

# IP: bd/block_design/ip/block_design_auto_pc_0/block_design_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_auto_pc_0 || ORIG_REF_NAME==block_design_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/John/Desktop/reconfig/reconfig/final_lab/final_lab_vivado/final_lab/final_lab.gen/sources_1/bd/block_design/block_design_ooc.xdc
