# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/lab2_part1/lab2_part1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab2_part1 || ORIG_REF_NAME==lab2_part1} -quiet] -quiet

# IP: bd/lab2_part1/ip/lab2_part1_processing_system7_0_0/lab2_part1_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab2_part1_processing_system7_0_0 || ORIG_REF_NAME==lab2_part1_processing_system7_0_0} -quiet] -quiet

# IP: bd/lab2_part1/ip/lab2_part1_my_multiplier_0_0/lab2_part1_my_multiplier_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab2_part1_my_multiplier_0_0 || ORIG_REF_NAME==lab2_part1_my_multiplier_0_0} -quiet] -quiet

# IP: bd/lab2_part1/ip/lab2_part1_ps7_0_axi_periph_0/lab2_part1_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab2_part1_ps7_0_axi_periph_0 || ORIG_REF_NAME==lab2_part1_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/lab2_part1/ip/lab2_part1_rst_ps7_0_100M_0/lab2_part1_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab2_part1_rst_ps7_0_100M_0 || ORIG_REF_NAME==lab2_part1_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/lab2_part1/ip/lab2_part1_auto_pc_0/lab2_part1_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab2_part1_auto_pc_0 || ORIG_REF_NAME==lab2_part1_auto_pc_0} -quiet] -quiet

# XDC: d:/Repos/reconfig/lab2/lab2.gen/sources_1/bd/lab2_part1/lab2_part1_ooc.xdc
