webtalk_init -webtalk_dir c:/users/john/desktop/reconfig/reconfig/final_lab/final_lab_vivado/final_lab/final_lab.tmp/accelerator_v1_0_project/accelerator_v1_0_project.sim/sim_1/behav/xsim/xsim.dir/wrapper_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Nov 29 23:32:51 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2021.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3247384" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "36d1741e-2734-47df-b0d0-11ede8af0cb7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "0f04f4d4a51a4fc091b45af9e8421fa6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "52" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3600 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "20490 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.44_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "22116_KB" -context "xsim\\usage"
webtalk_transmit -clientid 375566246 -regid "" -xml c:/users/john/desktop/reconfig/reconfig/final_lab/final_lab_vivado/final_lab/final_lab.tmp/accelerator_v1_0_project/accelerator_v1_0_project.sim/sim_1/behav/xsim/xsim.dir/wrapper_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html c:/users/john/desktop/reconfig/reconfig/final_lab/final_lab_vivado/final_lab/final_lab.tmp/accelerator_v1_0_project/accelerator_v1_0_project.sim/sim_1/behav/xsim/xsim.dir/wrapper_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm c:/users/john/desktop/reconfig/reconfig/final_lab/final_lab_vivado/final_lab/final_lab.tmp/accelerator_v1_0_project/accelerator_v1_0_project.sim/sim_1/behav/xsim/xsim.dir/wrapper_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
