# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Repos/reconfig/lab2/part2/lab2_part2/lab2_part2.srcs/sources_1/bd/part2/ip/part2_processing_system7_0_0/part2_processing_system7_0_0.xci
# IP: The module: 'part2_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Repos/reconfig/lab2/part2/lab2_part2/lab2_part2.gen/sources_1/bd/part2/ip/part2_processing_system7_0_0/part2_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'part2_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/Repos/reconfig/lab2/part2/lab2_part2/lab2_part2.srcs/sources_1/bd/part2/ip/part2_processing_system7_0_0/part2_processing_system7_0_0.xci
# IP: The module: 'part2_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Repos/reconfig/lab2/part2/lab2_part2/lab2_part2.gen/sources_1/bd/part2/ip/part2_processing_system7_0_0/part2_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'part2_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
