# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/part2/part2.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==part2 || ORIG_REF_NAME==part2} -quiet] -quiet

# IP: bd/part2/ip/part2_processing_system7_0_0/part2_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==part2_processing_system7_0_0 || ORIG_REF_NAME==part2_processing_system7_0_0} -quiet] -quiet

# IP: bd/part2/ip/part2_ps7_0_axi_periph_1/part2_ps7_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==part2_ps7_0_axi_periph_1 || ORIG_REF_NAME==part2_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/part2/ip/part2_rst_ps7_0_100M_1/part2_rst_ps7_0_100M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==part2_rst_ps7_0_100M_1 || ORIG_REF_NAME==part2_rst_ps7_0_100M_1} -quiet] -quiet

# IP: bd/part2/ip/part2_accelerator_0_0/part2_accelerator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==part2_accelerator_0_0 || ORIG_REF_NAME==part2_accelerator_0_0} -quiet] -quiet

# IP: bd/part2/ip/part2_auto_pc_0/part2_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==part2_auto_pc_0 || ORIG_REF_NAME==part2_auto_pc_0} -quiet] -quiet

# XDC: d:/Repos/reconfig/lab2/part2/lab2_part2/lab2_part2.gen/sources_1/bd/part2/part2_ooc.xdc
