# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Repos/reconfig/lab2/lab2.srcs/sources_1/bd/lab2_part1/ip/lab2_part1_rst_ps7_0_100M_0/lab2_part1_rst_ps7_0_100M_0.xci
# IP: The module: 'lab2_part1_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Repos/reconfig/lab2/lab2.gen/sources_1/bd/lab2_part1/ip/lab2_part1_rst_ps7_0_100M_0/lab2_part1_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab2_part1_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Repos/reconfig/lab2/lab2.gen/sources_1/bd/lab2_part1/ip/lab2_part1_rst_ps7_0_100M_0/lab2_part1_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab2_part1_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Repos/reconfig/lab2/lab2.gen/sources_1/bd/lab2_part1/ip/lab2_part1_rst_ps7_0_100M_0/lab2_part1_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab2_part1_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Repos/reconfig/lab2/lab2.srcs/sources_1/bd/lab2_part1/ip/lab2_part1_rst_ps7_0_100M_0/lab2_part1_rst_ps7_0_100M_0.xci
# IP: The module: 'lab2_part1_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Repos/reconfig/lab2/lab2.gen/sources_1/bd/lab2_part1/ip/lab2_part1_rst_ps7_0_100M_0/lab2_part1_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab2_part1_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Repos/reconfig/lab2/lab2.gen/sources_1/bd/lab2_part1/ip/lab2_part1_rst_ps7_0_100M_0/lab2_part1_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab2_part1_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Repos/reconfig/lab2/lab2.gen/sources_1/bd/lab2_part1/ip/lab2_part1_rst_ps7_0_100M_0/lab2_part1_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab2_part1_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
