# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/zynq_proc/zynq_proc.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_proc || ORIG_REF_NAME==zynq_proc} -quiet] -quiet

# IP: bd/zynq_proc/ip/zynq_proc_processing_system7_0_0/zynq_proc_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_proc_processing_system7_0_0 || ORIG_REF_NAME==zynq_proc_processing_system7_0_0} -quiet] -quiet

# IP: bd/zynq_proc/ip/zynq_proc_accelerator_0_0/zynq_proc_accelerator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_proc_accelerator_0_0 || ORIG_REF_NAME==zynq_proc_accelerator_0_0} -quiet] -quiet

# IP: bd/zynq_proc/ip/zynq_proc_ps7_0_axi_periph_0/zynq_proc_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_proc_ps7_0_axi_periph_0 || ORIG_REF_NAME==zynq_proc_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/zynq_proc/ip/zynq_proc_rst_ps7_0_100M_0/zynq_proc_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_proc_rst_ps7_0_100M_0 || ORIG_REF_NAME==zynq_proc_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/zynq_proc/ip/zynq_proc_auto_pc_0/zynq_proc_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_proc_auto_pc_0 || ORIG_REF_NAME==zynq_proc_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/John/Desktop/reconig/reconfig/lab5/part2/lab5part2_vivado/lab5part2_vivado.gen/sources_1/bd/zynq_proc/zynq_proc_ooc.xdc
