# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/John/Desktop/reconfig/reconfig/final_lab/final_lab_vivado/final_lab/final_lab.srcs/sources_1/bd/block_design/ip/block_design_auto_pc_0/block_design_auto_pc_0.xci
# IP: The module: 'block_design_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/John/Desktop/reconfig/reconfig/final_lab/final_lab_vivado/final_lab/final_lab.gen/sources_1/bd/block_design/ip/block_design_auto_pc_0/block_design_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_design_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/John/Desktop/reconfig/reconfig/final_lab/final_lab_vivado/final_lab/final_lab.srcs/sources_1/bd/block_design/ip/block_design_auto_pc_0/block_design_auto_pc_0.xci
# IP: The module: 'block_design_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/John/Desktop/reconfig/reconfig/final_lab/final_lab_vivado/final_lab/final_lab.gen/sources_1/bd/block_design/ip/block_design_auto_pc_0/block_design_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_design_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
