# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/John/Desktop/reconig/reconfig/lab5/part2/lab5part2_vivado/lab5part2_vivado.srcs/sources_1/bd/zynq_proc/ip/zynq_proc_rst_ps7_0_100M_0/zynq_proc_rst_ps7_0_100M_0.xci
# IP: The module: 'zynq_proc_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/John/Desktop/reconig/reconfig/lab5/part2/lab5part2_vivado/lab5part2_vivado.gen/sources_1/bd/zynq_proc/ip/zynq_proc_rst_ps7_0_100M_0/zynq_proc_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_proc_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/John/Desktop/reconig/reconfig/lab5/part2/lab5part2_vivado/lab5part2_vivado.gen/sources_1/bd/zynq_proc/ip/zynq_proc_rst_ps7_0_100M_0/zynq_proc_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_proc_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/John/Desktop/reconig/reconfig/lab5/part2/lab5part2_vivado/lab5part2_vivado.gen/sources_1/bd/zynq_proc/ip/zynq_proc_rst_ps7_0_100M_0/zynq_proc_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_proc_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/John/Desktop/reconig/reconfig/lab5/part2/lab5part2_vivado/lab5part2_vivado.srcs/sources_1/bd/zynq_proc/ip/zynq_proc_rst_ps7_0_100M_0/zynq_proc_rst_ps7_0_100M_0.xci
# IP: The module: 'zynq_proc_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/John/Desktop/reconig/reconfig/lab5/part2/lab5part2_vivado/lab5part2_vivado.gen/sources_1/bd/zynq_proc/ip/zynq_proc_rst_ps7_0_100M_0/zynq_proc_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_proc_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/John/Desktop/reconig/reconfig/lab5/part2/lab5part2_vivado/lab5part2_vivado.gen/sources_1/bd/zynq_proc/ip/zynq_proc_rst_ps7_0_100M_0/zynq_proc_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_proc_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/John/Desktop/reconig/reconfig/lab5/part2/lab5part2_vivado/lab5part2_vivado.gen/sources_1/bd/zynq_proc/ip/zynq_proc_rst_ps7_0_100M_0/zynq_proc_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_proc_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
